export interface EtlSourceInfo {
  id: string;
  name: string;
  organization: string;
  category: "personal" | "finanzas" | "compras" | "probidad" | "parlamento" | "municipios";
  frequency: string;
  lastUpdated: string;
  lastUpdatedRelative: string;
  recordCount: number;
  financialAmountClp?: number;
  status: "operational" | "updated" | "official_lag";
  statusText: string;
  officialUrl: string;
  description: string;
  keyFields: string[];
  viewLink: string;
  viewLabel: string;
}

export const ETL_SOURCES_DATA: EtlSourceInfo[] = [
  {
    id: "etl_cplt_transparencia_activa",
    name: "Transparencia Activa CPLT",
    organization: "Consejo para la Transparencia (CPLT)",
    category: "personal",
    frequency: "Mensual (Cortes mes vencido)",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (Sincronización automatizada)",
    recordCount: 1203287,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://www.consejotransparencia.cl/datos-abiertos/",
    description: "Nóminas de dotación completa (Planta, Contrata, Honorarios y Código del Trabajo) de 323 organismos del Estado.",
    keyFields: ["RUT", "Nombre Completo", "Cargo", "Grado EUS", "Remuneración Bruta", "Horas Extras"],
    viewLink: "/funcionarios",
    viewLabel: "Ver buscador de funcionarios →",
  },
  {
    id: "etl_dipres_presupuestos",
    name: "Ley de Presupuestos de la Nación",
    organization: "Dirección de Presupuestos (DIPRES) · Ministerio de Hacienda",
    category: "finanzas",
    frequency: "Anual con seguimiento trimestral",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (Ley 2026 consolidada)",
    recordCount: 476,
    financialAmountClp: 83420000000000,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://www.dipres.gob.cl/598/w3-propertyvalue-15199.html",
    description: "Presupuesto nacional de Chile catalogado por 33 Partidas, Capítulos y 476 Programas con subtítulos de gasto.",
    keyFields: ["Partida", "Capítulo", "Programa", "Presupuesto Inicial", "Presupuesto Vigente", "Devengado"],
    viewLink: "/servicios-publicos",
    viewLabel: "Ver presupuesto por ministerios →",
  },
  {
    id: "etl_ley_19862_transferencias",
    name: "Registro Central de Colaboradores (Ley 19.862)",
    organization: "Ministerio de Hacienda · registros19862.gob.cl",
    category: "finanzas",
    frequency: "Mensual",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (Período 2023-2026)",
    recordCount: 361101,
    financialAmountClp: 17688240000000,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://www.registros19862.gob.cl/",
    description: "Transferencias y fondos públicos entregados a 61.336 fundaciones, corporaciones, ONGs y personas jurídicas.",
    keyFields: ["RUT Receptor", "Organismo Emisor", "Monto CLP", "Resolución Exenta", "Materia"],
    viewLink: "/transferencias",
    viewLabel: "Ver dashboard de transferencias →",
  },
  {
    id: "etl_chilecompra_ocds",
    name: "ChileCompra / MercadoPúblico OCDS",
    organization: "Dirección ChileCompra · API Estándar OCDS",
    category: "compras",
    frequency: "Semanal / Actualización continua",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (36.813 procesos)",
    recordCount: 74142,
    financialAmountClp: 124230000000000,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://datos-abiertos.chilecompra.cl/",
    description: "Licitaciones, órdenes de compra y contratos del Estado bajo el estándar internacional Open Contracting Data Standard.",
    keyFields: ["ID Licitación", "Comprador", "Proveedor Adjudicado", "Monto CLP", "RUT", "Tipo Proceso"],
    viewLink: "/cruces",
    viewLabel: "Ver compras en explorador de cruces →",
  },
  {
    id: "etl_infolobby_plataforma",
    name: "Plataforma InfoLobby",
    organization: "Consejo para la Transparencia (CPLT) · Ley 20.730",
    category: "probidad",
    frequency: "Diaria",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (Audiencias 2024-2026)",
    recordCount: 60334,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://www.infolobby.cl/",
    description: "Registro de audiencias sostenidas por lobistas y gestores de intereses con autoridades y directivos públicos.",
    keyFields: ["Sujeto Pasivo", "Institución", "Gestor de Interés", "Materias Tratadas", "Fecha Audiencia"],
    viewLink: "/cruces#lobby-publico",
    viewLabel: "Ver audiencias en explorador →",
  },
  {
    id: "etl_infoprobidad_declaraciones",
    name: "Declaraciones de Intereses y Patrimonio",
    organization: "Contraloría General de la República · CPLT · Ley 20.880",
    category: "probidad",
    frequency: "Anual / Por cese o asunción de cargo",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (Período 2024-2026)",
    recordCount: 13387,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://www.declaracionjurada.cl/",
    description: "Declaraciones juradas de bienes, participaciones en sociedades, inmuebles y vehículos de autoridades públicas.",
    keyFields: ["Declarante", "Cargo", "Institución", "Activos", "Sociedades", "Fecha Declaración"],
    viewLink: "/personas",
    viewLabel: "Ver declaraciones de autoridades →",
  },
  {
    id: "etl_sinim_subdere",
    name: "Sistema Nacional de Información Municipal (SINIM)",
    organization: "SUBDERE · Ministerio del Interior",
    category: "municipios",
    frequency: "Trimestral / Anual",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (346 comunas)",
    recordCount: 3105,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "http://www.sinim.gov.cl/",
    description: "Ingresos propios, Fondo Común Municipal (FCM), gasto en personal e inversión comunal de los 346 municipios de Chile.",
    keyFields: ["Código Comuna", "Nombre Comuna", "Ingresos Propios", "FCM", "Gasto Personal", "Inversión"],
    viewLink: "/municipalidades",
    viewLabel: "Ver comparador de 346 comunas →",
  },
  {
    id: "etl_contraloria_auditorias",
    name: "Informes de Auditoría CGR",
    organization: "Contraloría General de la República de Chile",
    category: "probidad",
    frequency: "Continua (Publicación de informes)",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (Informes consolidados)",
    recordCount: 275,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://www.contraloria.cl/web/cgr/informes-de-auditoria",
    description: "Auditorías especiales, exámenes de cuentas e investigaciones especiales sobre el uso de recursos fiscales.",
    keyFields: ["N° Informe", "Entidad Auditada", "Materia", "Observaciones", "Fecha Publicación"],
    viewLink: "/cruces#fiscalizacion",
    viewLabel: "Ver fiscalizaciones en explorador →",
  },
  {
    id: "etl_camara_diputados",
    name: "Cámara de Diputadas y Diputados de Chile",
    organization: "Congreso Nacional de Chile · opendata.camara.cl",
    category: "parlamento",
    frequency: "Por sesión legislativa",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (155 diputados)",
    recordCount: 28370,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://opendata.camara.cl/",
    description: "Votaciones nominales de Sala, asistencias por sesión convocada y rendición mensual de gastos operacionales.",
    keyFields: ["ID Diputado", "Sesión", "Boletín", "Sentido Voto", "Estado Asistencia", "Gastos"],
    viewLink: "/politico",
    viewLabel: "Ver análisis de diputados →",
  },
  {
    id: "etl_senado_republica",
    name: "Senado de la República de Chile",
    organization: "Congreso Nacional de Chile · opendata.senado.cl",
    category: "parlamento",
    frequency: "Por sesión legislativa",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Hoy (50 senadores)",
    recordCount: 8151,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://www.senado.cl/transparencia/datos-abiertos",
    description: "Votaciones de Sala, asistencia a comisiones, justificaciones de inasistencia y gastos operacionales.",
    keyFields: ["ID Senador", "Sesión", "Boletín", "Voto", "Asistencia a Sala", "Gastos"],
    viewLink: "/politico",
    viewLabel: "Ver análisis de senadores →",
  },
  {
    id: "etl_servel_electoral",
    name: "SERVEL (Resultados Electorales)",
    organization: "Servicio Electoral de Chile (SERVEL)",
    category: "parlamento",
    frequency: "Por ciclo electoral oficial",
    lastUpdated: "2026-08-16T01:45:00.000Z",
    lastUpdatedRelative: "Período 2024-2025 consolidado",
    recordCount: 205,
    status: "operational",
    statusText: "100% Operativo",
    officialUrl: "https://www.servel.cl/resultados-electorales/",
    description: "Resultados oficiales de votación de autoridades electas, coaliciones políticas y padrón electoral.",
    keyFields: ["ID Candidato", "Votos Obtenidos", "Porcentaje", "Pacto", "Partido"],
    viewLink: "/partidos",
    viewLabel: "Ver partidos y escaños →",
  },
];
