/**
 * seremis.ts — Secretarios Regionales Ministeriales del Gobierno de José Antonio Kast (2026-2030).
 * Solo datos con fuente (ministerios oficiales, delegaciones presidenciales y prensa regional con fecha).
 * Reglas de calidad:
 *  - Donde hubo renuncia/desistimiento se registra al titular vigente y se anota el cambio en «nota».
 *  - Donde dos fuentes discrepan se mantiene la de fecha más reciente y se anotan ambas.
 *  - Los cupos sin nombre confirmado quedan fuera (no se inventan autoridades).
 *
 * Fuentes principales:
 *  - minagri.gob.cl (30-03-2026 y 02-04-2026): nómina Agricultura 16/16 regiones
 *  - minsal.cl (26-03-2026): nómina Salud por región
 *  - Delegaciones presidenciales: dprarica, dprtarapaca, dprantofagasta, dprnuble, dprlosrios, dpraysen, dprmagallanes, dprmetropolitana, dprlaaraucania
 *  - Prensa regional con fecha: radioatacama/tierramarillano, elcontraste/latribuna/diarioconcepcion, diarioelmarino,
 *    diarioelcentro/vlnradio, quintavisionahora/concagua, rioenlinea/diariopaillaco/radioaustral, patagoniaradio/cooperativo,
 *    elmagallanews/itvpatagonia/portal12, diarioregionalaysen, elmorrocotudo/vilasradio, diarioeldia/laserenaonline.
 */

export interface Seremi {
  region: string;
  cartera: string;
  nombre: string;
  fuente: string;
  nota?: string;
}

export const SEREMIS: Seremi[] = [
  // ==== AGRICULTURA — nómina oficial minagri.gob.cl (30-03 y 02-04-2026, 16/16) ====
  { region: "Arica y Parinacota", cartera: "Agricultura", nombre: "Jorge Heiden Campello", fuente: "minagri.gob.cl 30-03-2026" },
  { region: "Tarapacá", cartera: "Agricultura", nombre: "Fernando Chiffelle Ruff", fuente: "minagri.gob.cl 30-03-2026" },
  { region: "Antofagasta", cartera: "Agricultura", nombre: "Harry Pallero Muñoz", fuente: "minagri.gob.cl 02-04-2026" },
  { region: "Atacama", cartera: "Agricultura", nombre: "Guillermo Procuriza Naim", fuente: "minagri.gob.cl 30-03-2026", nota: "la prensa regional lo registró como «Willy Procuricka»" },
  { region: "Coquimbo", cartera: "Agricultura", nombre: "Vicente Cortés Varela", fuente: "minagri.gob.cl 30-03-2026 · diarioeldía" },
  { region: "Valparaíso", cartera: "Agricultura", nombre: "Nicolás Prado García-Huidobro", fuente: "minagri.gob.cl 30-03-2026" },
  { region: "Metropolitana", cartera: "Agricultura", nombre: "Fernando Rencoret Gómez", fuente: "minagri.gob.cl 30-03-2026" },
  { region: "O'Higgins", cartera: "Agricultura", nombre: "Carlos Valdés Errázuriz", fuente: "minagri.gob.cl 30-03-2026 · diarioelmarino" },
  { region: "Maule", cartera: "Agricultura", nombre: "Alejando Muñoz Ávalos", fuente: "minagri.gob.cl 30-03-2026 · diarioelcentro" },
  { region: "Ñuble", cartera: "Agricultura", nombre: "Juan Luis Enríquez Fuentes", fuente: "minagri.gob.cl 30-03-2026" },
  { region: "Biobío", cartera: "Agricultura", nombre: "Francisco Lagos Arriagada", fuente: "minagri.gob.cl 30-03-2026 · elcontraste" },
  { region: "La Araucanía", cartera: "Agricultura", nombre: "María Teresa Fernández Cabrera", fuente: "minagri.gob.cl 30-03-2026" },
  { region: "Los Ríos", cartera: "Agricultura", nombre: "Rodrigo Bahamondes Flores", fuente: "minagri.gob.cl 30-03-2026" },
  { region: "Aysén", cartera: "Agricultura", nombre: "Yordy Cea España", fuente: "minagri.gob.cl 30-03-2026" },
  { region: "Magallanes", cartera: "Agricultura", nombre: "Juan Ignacio Cavada", fuente: "minagri.gob.cl 02-04-2026" },

  // ==== SALUD — fuente minsal.cl (26-03-2026) + prensa ====
  { region: "Arica y Parinacota", cartera: "Salud", nombre: "Karla Kepec Álvarez", fuente: "minsal 26-03-2026 · elmorrocotudo" },
  { region: "Antofagasta", cartera: "Salud", nombre: "Rodrigo Medina Vera", fuente: "minsal.cl 26-03-2026", nota: "médico, atención primaria" },
  { region: "Atacama", cartera: "Salud", nombre: "Silvana Flores", fuente: "radioatacama 26-03-2026", nota: "en julio 2026 figura Richard González Gálvez como seremi (s)" },
  { region: "Coquimbo", cartera: "Salud", nombre: "Karen Irribarra", fuente: "diarioelcentro 30-03-2026", nota: "matrona" },
  { region: "Valparaíso", cartera: "Salud", nombre: "Mariola Luán", fuente: "aconcaguaaldia.cl 15-04-2026", nota: "reemplaza a Aldo Ibani, quien renunció a los 3 días (latercera 06-04-2026)" },
  { region: "Metropolitana", cartera: "Salud", nombre: "Pía Venegas Araneda", fuente: "minsal.cl 26-03-2026", nota: "enfermera, magíster en epidemiología" },
  { region: "O'Higgins", cartera: "Salud", nombre: "Daniela Zavando Matamala", fuente: "minsal.cl 26-03-2026", nota: "cirujano dentista, ex suceremi en RM y O'Higgins" },
  { region: "Maule", cartera: "Salud", nombre: "Iskra Cox", fuente: "24horas/vlnradio 26-03-2026", nota: "cirujano dentista, ex directora del SML regional" },
  { region: "Ñuble", cartera: "Salud", nombre: "Jorge Carrillo", fuente: "dprnuble.dpr.gob.cl 26-03-2026", nota: "nutricionista" },
  { region: "Biobío", cartera: "Salud", nombre: "Isabel Rojas Salfate", fuente: "minsal.cl 26-03-2026 · elcontraste", nota: "psicóloga" },
  { region: "La Araucanía", cartera: "Salud", nombre: "José Bravo Burgos", fuente: "minsal 26-03-2026" },
  { region: "Los Ríos", cartera: "Salud", nombre: "Felipe Bastidas Espinoza", fuente: "dprlosrios.dpr.gob.cl 26-03-2026", nota: "cirujano dentista" },
  { region: "Los Lagos", cartera: "Salud", nombre: "Evelyn Brintrup Flores", fuente: "patagoniaradio 26-03-2026" },
  { region: "Aysén", cartera: "Salud", nombre: "Jorge Pérez", fuente: "diarioregionalaysen 26-03-2026", nota: "enfermero (PSC)" },
  { region: "Magallanes", cartera: "Salud", nombre: "Fabián Barrientos Andrade", fuente: "itvpatagonia.com 27-03-2026" },

  // ==== ARICA Y PARINACOTA — gabinete completo (21 cargos) dprarica 01-04-2026 ====
  { region: "Arica y Parinacota", cartera: "Hacienda", nombre: "Marcelo Vergara Albarracín", fuente: "dprarica 01-04-2026", nota: "PRCh" },
  { region: "Arica y Parinacota", cartera: "Gobierno (Segegob)", nombre: "Pollyana Rivera Bigas", fuente: "dprarica 01-04-2026", nota: "PRCh" },
  { region: "Arica y Parinacota", cartera: "Economía", nombre: "Romina Cifuentes González", fuente: "dprarica 01-04-2026", nota: "PRCh" },
  { region: "Arica y Parinacota", cartera: "Desarrollo Social", nombre: "Paulina Gálvez Melgar", fuente: "dprarica 01-04-2026", nota: "Demócratas" },
  { region: "Arica y Parinacota", cartera: "Educación", nombre: "Pía Urrutia Iglesias", fuente: "dprarica 01-04-2026", nota: "UDI" },
  { region: "Arica y Parinacota", cartera: "Justicia", nombre: "Matías Andrade Gálvez", fuente: "dprarica 01-04-2026", nota: "PRCh" },
  { region: "Arica y Parinacota", cartera: "Seguridad Pública", nombre: "Pedro Álvarez Ortega", fuente: "dprarica 01-04-2026", nota: "PRCh" },
  { region: "Arica y Parinacota", cartera: "Trabajo", nombre: "Natalie Cruz Plaza", fuente: "dprarica 01-04-2026", nota: "PSC; renunció el 09-04-2026 a los 8 días por no acreditar experiencia laboral mínima (elmostrador); cupo en evaluación" },
  { region: "Arica y Parinacota", cartera: "Obras Públicas", nombre: "Luis Hernández Quevedo", fuente: "dprarica 01-04-2026", nota: "Demócratas" },
  { region: "Arica y Parinacota", cartera: "Vivienda", nombre: "Francisco Meza Hernández", fuente: "dprarica 01-04-2026", nota: "UDI" },
  { region: "Arica y Parinacota", cartera: "Minería", nombre: "Mauro Hidalgo Morales", fuente: "dprarica 01-04-2026", nota: "PRCh" },
  { region: "Arica y Parinacota", cartera: "Transportes", nombre: "Patricio Lörd Tapia", fuente: "dprarica 01-04-2026", nota: "PRCh" },
  { region: "Arica y Parinacota", cartera: "Bienes Nacionales", nombre: "Cristian Pradenas Soto", fuente: "dprarica 01-04-2026", nota: "PNL" },
  { region: "Arica y Parinacota", cartera: "Energía", nombre: "Carlos Ferrada Cabrera", fuente: "dprarica 01-04-2026", nota: "IND" },
  { region: "Arica y Parinacota", cartera: "Medio Ambiente", nombre: "Raúl Gil González", fuente: "dprarica 01-04-2026", nota: "UDI" },
  { region: "Arica y Parinacota", cartera: "Deporte", nombre: "Alberto Labra Pérez", fuente: "dprarica 01-04-2026", nota: "IND" },
  { region: "Arica y Parinacota", cartera: "Mujer", nombre: "Greissy Cofré Mancilla", fuente: "dprarica 01-04-2026", nota: "UDI" },
  { region: "Arica y Parinacota", cartera: "Culturas", nombre: "Hernán Zamora Salinas", fuente: "dprarica 01-04-2026", nota: "RN" },
  { region: "Arica y Parinacota", cartera: "Ciencia", nombre: "Juan Claudio Mancilla", fuente: "dprarica 01-04-2026", nota: "RN" },

  // ==== TARAPACÁ — gabinete completo dprtarapaca 30-03-2026 + elboyaldia 26-03-2026 ====
  { region: "Tarapacá", cartera: "Seguridad Pública", nombre: "Eduardo Salazar Méndez", fuente: "dprtarapaca 30-03-2026", nota: "teniente coronel (R) de Carabineros" },
  { region: "Tarapacá", cartera: "Gobierno (Segegob)", nombre: "Yuseff Hilaja Rumié", fuente: "dprtarapaca 30-03-2026", nota: "periodista" },
  { region: "Tarapacá", cartera: "Justicia", nombre: "Claudio Chamorro Olguín", fuente: "dprtarapaca 30-03-2026", nota: "abogado, ex director de Migraciones regional" },
  { region: "Tarapacá", cartera: "Trabajo", nombre: "Cristián Andrés Cabezas Mundaca", fuente: "dprtarapaca 30-03-2026", nota: "profesor, ex candidato a gobernador" },
  { region: "Tarapacá", cartera: "Minería", nombre: "Gonzalo Vidal Capiccelli", fuente: "dprtarapaca 30-03-2026", nota: "periodista, jefe de gestión del MOP regional" },
  { region: "Tarapacá", cartera: "Energía", nombre: "Juan Ignacio Boudon Huberman", fuente: "dprtarapaca 30-03-2026", nota: "ex director regional de CONAF" },
  { region: "Tarapacá", cartera: "Deporte", nombre: "Felipe Eduardo Pérez Contreras", fuente: "dprtarapaca 30-03-2026", nota: "ex seremi en 2.º gobierno de Piñera" },
  { region: "Tarapacá", cartera: "Mujer", nombre: "Lucrecia Mena Acosta", fuente: "dprtarapaca 30-03-2026", nota: "trabajadora social, ex Senama" },
  { region: "Tarapacá", cartera: "Culturas", nombre: "Álvaro Waldemar Gómez Vega", fuente: "dprtarapaca 30-03-2026", nota: "administrador público" },
  { region: "Tarapacá", cartera: "Ciencia", nombre: "Francisco Javier Bravo Silva", fuente: "dprtarapaca 30-03-2026", nota: "químico (U. de Tarapacá)" },
  { region: "Tarapacá", cartera: "Medio Ambiente", nombre: "Miguel Aguirre San Martín", fuente: "elboyaldia 30-03-2026", nota: "ing. civil mecánico" },
  { region: "Tarapacá", cartera: "Desarrollo Social", nombre: "Katherine Flores Alvarado", fuente: "dprtarapaca 30-03-2026 · midesof.gob.cl", nota: "administradora pública" },
  { region: "Tarapacá", cartera: "Obras Públicas", nombre: "Enrique Martínez Arteaga", fuente: "dpr.gob.cl 31-03-2026 · soychile.cl 31-03-2026 · radiopaulina.cl 31-03-2026", nota: "ing. constructor, ex inspector técnico MOP; sucede a Mauricio Montealegre Gandolfo, quien desistió antes de asumir" },
  { region: "Tarapacá", cartera: "Educación", nombre: "Leonardo Hermógenes Gálvez Castro", fuente: "dprtarapaca 26-03-2026", nota: "profesor de Estado" },
  { region: "Tarapacá", cartera: "Salud", nombre: "Ximena del Pilar Muñoz Urbina", fuente: "minsal.cl 26-03-2026", nota: "médico veterinario" },
  { region: "Tarapacá", cartera: "Economía", nombre: "Gladys del Carmen Femenías González", fuente: "elboyaldia 26-03-2026", nota: "ing. civil industrial, ex directora de Empresa Portuaria de Iquique" },
  { region: "Tarapacá", cartera: "Vivienda", nombre: "Alonso Velásquez", fuente: "elboyaldia 26-03-2026", nota: "abogado U. Arturo Prat" },
  { region: "Tarapacá", cartera: "Bienes Nacionales", nombre: "Diego Muñoz", fuente: "radiopaulina 27-03-2026", nota: "abogado, procurador fiscal de Iquique" },

  // ==== ATACAMA — gabinete 19 cargos radioatacama 26-03 + atacama.mop.gob.cl ====
  { region: "Atacama", cartera: "Energía", nombre: "Manuel Nanjari", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Trabajo", nombre: "Pavel Weibel Bravo", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Gobierno (Segegob)", nombre: "Kyle Campbell", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Deporte", nombre: "Isis Martínez", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Justicia", nombre: "Carolina Rigers", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Educación", nombre: "Yoris Rojas", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Economía", nombre: "Daniela Gallegos", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Obras Públicas", nombre: "Paula Guerrero", fuente: "atacama.mop.cl 27-03-2026", nota: "ingeniera civil industrial" },
  { region: "Atacama", cartera: "Vivienda", nombre: "Max Barrionuevo", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Medio Ambiente", nombre: "David Olivares", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Mujer", nombre: "Nathalie Mardones", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Minería", nombre: "Jonathan Carmona", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Bienes Nacionales", nombre: "Joaquín Rodríguez", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Culturas", nombre: "Fernando Serrano", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Seguridad Pública", nombre: "Félix Vega", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Desarrollo Social", nombre: "Jessica Gómez", fuente: "radioatacama 26-03-2026" },
  { region: "Atacama", cartera: "Transportes", nombre: "Benjamín Quinela", fuente: "tierramarillano 27-03-2026", nota: "radioatacama 26-03 lo registró como Javier Díaz" },

  // ==== ANTOFAGASTA — dprantofagasta + prensa ====
  { region: "Antofagasta", cartera: "Educación", nombre: "Carolina Moscoso Carrasco", fuente: "dprantofagasta 25-03-2026", nota: "Partido Social Cristiano" },
  { region: "Antofagasta", cartera: "Medio Ambiente", nombre: "Verónica Araneda Álvarez", fuente: "dprantofagasta 25-03-2026" },
  { region: "Antofagasta", cartera: "Seguridad Pública", nombre: "Cristian Bravo Echeverría", fuente: "antofagastaonline 27-03-2026", nota: "prefecto (R) de la PDI" },
  { region: "Antofagasta", cartera: "Economía", nombre: "Pablo Pomareda Echeverría", fuente: "antofagastaonline 27-03-2026" },
  { region: "Antofagasta", cartera: "Vivienda", nombre: "Jorge Olivares Puentes", fuente: "antofagastaonline 27-03-2026" },
  { region: "Antofagasta", cartera: "Justicia", nombre: "Karina Trujillo Contreras", fuente: "antofagastaonline 27-03-2026", nota: "renunció 14-04-2026 (latercera/Eldinamo); minjusticia listaba a Ramón Tagle — cupo en revisión" },
  { region: "Antofagasta", cartera: "Bienes Nacionales", nombre: "Patricio Martínez Quinzacara", fuente: "antofagasta.cl", nota: "asume tras renuncia de Camila Alonso Kluget" },
  { region: "Antofagasta", cartera: "Obras Públicas", nombre: "José Fuentes Villanueva", fuente: "antofagastaonline 27-03-2026" },
  { region: "Antofagasta", cartera: "Desarrollo Social", nombre: "Lizet Tapia Martin", fuente: "latercera 24-04-2026", nota: "no cumplió requisito académico (10 semestres); renunció" },
  { region: "Antofagasta", cartera: "Mujer", nombre: "Darioleta Vilch Bovet", fuente: "antofagasta.tv 22-04-2026 · calamaenlinea.cl 22-04-2026 · desiertofm.cl 22-04-2026", nota: "trabajadora social U. Autónoma; sucede a Anggel Colque, quien renunció el 08-04 por no contar con título profesional" },

  // ==== COQUIMBO — gabinete completo (20 cargos) diario el Día / laserenaonline 30-31-03 ====
  { region: "Coquimbo", cartera: "Gobierno (Segegob)", nombre: "Darwin Cortés Palma", fuente: "regional 30-03-2026", nota: "periodista, exconcejal de Canela" },
  { region: "Coquimbo", cartera: "Culturas", nombre: "Darwin Castro Aouvar", fuente: "diarioeldía 30-03-2026", nota: "periodista, jefe de gabinete del GORE" },
  { region: "Coquimbo", cartera: "Medio Ambiente", nombre: "Jovanka Rendic", fuente: "diarioeldía 30-03-2026", nota: "ingeniera, ex Subsecretaría de Pesca" },
  { region: "Coquimbo", cartera: "Educación", nombre: "Marcelo Salvo", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Economía", nombre: "Martín Peralta", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Vivienda", nombre: "Pablo Cuadra Corrales", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Obras Públicas", nombre: "Pablo Smitmans", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Deporte", nombre: "Ismael Zapata Frías", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Mujer", nombre: "Rudy Rivera Bugueño", fuente: "diarioeldía 30-03-2026", nota: "perfil con trayectoria municipal" },
  { region: "Coquimbo", cartera: "Trabajo", nombre: "Viviana Torres Olivares", fuente: "diarioeldía 30-03-2026", nota: "renunció a fines de abril por no cumplir el requisito de carrera mínima de 10 semestres (información confirmada)" },
  { region: "Coquimbo", cartera: "Transportes", nombre: "Marcelo Rojas", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Justicia", nombre: "Humberto Bermúdez", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Bienes Nacionales", nombre: "Gloria Paredes Díaz", fuente: "bienesnacionales.cl 27-03-2026" },
  { region: "Coquimbo", cartera: "Desarrollo Social", nombre: "Carlos Cortés", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Seguridad Pública", nombre: "María José Duarte Flores", fuente: "diarioeldía 30-03-2026", nota: "abogada" },
  { region: "Coquimbo", cartera: "Ciencia", nombre: "Maité Arenas Rojas", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Minería", nombre: "Juan Carlos Salinas Maraboli", fuente: "diarioeldía 30-03-2026" },
  { region: "Coquimbo", cartera: "Energía", nombre: "Fabián Páez Leyton", fuente: "diarioeldía 30-03-2026" },

  // ==== VALPARAÍSO — elproa 31-03 (7) + quintavisionahora/aconcagua ====
  { region: "Valparaíso", cartera: "Gobierno (Segegob)", nombre: "Rosario Pérez Izquierdo", fuente: "elproa 31-03-2026" },
  { region: "Valparaíso", cartera: "Seguridad Pública", nombre: "Hernán Eduardo Silva Llagostera", fuente: "elproa 31-03-2026", nota: "coronel (R); sumariado por presunta falsificación de firmas — luego ratificado (latercera 24-04)" },
  { region: "Valparaíso", cartera: "Justicia", nombre: "Rafael González Camus", fuente: "elproa 31-03-2026 · encancha.cl 01-04-2026", nota: "ex presidente de Wanderers" },
  { region: "Valparaíso", cartera: "Bienes Nacionales", nombre: "Leslie Andrea Cornejo Medina", fuente: "elproa 31-03-2026" },
  { region: "Valparaíso", cartera: "Culturas", nombre: "Catalina Dib Puelma", fuente: "elproa 31-03-2026" },
  { region: "Valparaíso", cartera: "Deporte", nombre: "Fernando López", fuente: "elproa 31-03-2026 · duplos.cl 01-04-2026" },
  { region: "Valparaíso", cartera: "Mujer", nombre: "Pamela Reyes", fuente: "elproa 31-03-2026", nota: "nombre compuesto a verificar" },
  { region: "Valparaíso", cartera: "Trabajo", nombre: "Carolina Sangüesa", fuente: "aconcagua 15-04-2026", nota: "ex directora regional del Sernac; reemplaza a Carlos Madrid, quien renunció el 07-04" },
  { region: "Valparaíso", cartera: "Minería", nombre: "Cristian Vasseur Fuentes", fuente: "aconcaguaaldia.cl 23-04-2026 · soychile.cl 23-04-2026 · reporteminero.cl", nota: "ing. comercial, nombrado por el delegado presidencial Manuel Millones; sucede a Benjamín Koch, quien declinó antes de oficializarse" },

  // ==== METROPOLITANA — varias fuentes con fecha ====
  { region: "Metropolitana", cartera: "Vivienda", nombre: "Sebastián Norambuena Navarro", fuente: "minvu / acta COSOC 15-04-2026" },
  { region: "Metropolitana", cartera: "Educación", nombre: "Stefanie Wenderoth", fuente: "linkedin/seremi13.redsalud 13-04-2026", nota: "profesora; grafía a verificar" },
  { region: "Metropolitana", cartera: "Culturas", nombre: "Renato Münster", fuente: "theclinic.cl 15-04-2026", nota: "1.º Gustavo Baehr renunció (15 días), 2.º Münster renunció a 24 h, 3.º asume Francisco Sólanich (cultura.gob.cl 24-04)" },
  { region: "Metropolitana", cartera: "Culturas", nombre: "Francisco Sólanich Aguirre", fuente: "cultura.gob.cl 24-04-2026", nota: "asume el 27-04 tras la cadena de renuncias" },
  { region: "Metropolitana", cartera: "Bienes Nacionales", nombre: "Heinz Alejandro Almendares Müller", fuente: "Diario Oficial dto. 36/2026 · leylobby.gob.cl 27-03-2026 · bienesnacionales.cl 08-04-2026", nota: "concejal RN de Maipú 2012-2024; sucesor de Carol Castro (dto. 45/2024, gobierno de Boric)" },
  { region: "Metropolitana", cartera: "Economía", nombre: "Juan Pablo Piera Morales", fuente: "economia.gob.cl (seremis RM) · Corfo RM 06-04-2026", nota: "no es Cristián Rodríguez (seremi de Boric); designación del gobierno de Kast" },
  { region: "Metropolitana", cartera: "Minería", nombre: "Paluksa Solar", fuente: "elindustrial.cl 05-06-2026 · amagazine.cl 05-06-2026", nota: "seremi de Minería RM; sucesora de Carlos Hunt (gobierno de Boric)" },
  { region: "Metropolitana", cartera: "Desarrollo Social", nombre: "Kattia Durán Álvarez", fuente: "midesof.gob.cl (Seremi RM, 02-04-2026)" },

  // ==== O'HIGGINS — diarioelmarino 30-03 (13 cargos) ====
  { region: "O'Higgins", cartera: "Gobierno (Segegob)", nombre: "Matías Ignacio Riveros Jara", fuente: "diarioelmarino 30-03-2026", nota: "cientista político" },
  { region: "O'Higgins", cartera: "Seguridad Pública", nombre: "Nicolás Ignacio Muñoz Muñoz", fuente: "diarioelmarino 30-03-2026", nota: "ex oficial de Carabineros" },
  { region: "O'Higgins", cartera: "Justicia", nombre: "Alejandro Luis Zúñiga Tapia", fuente: "diarioelmarino 30-03-2026 · CVE-2839265 14-05-2026" },
  { region: "O'Higgins", cartera: "Energía", nombre: "Alejandra Avendaño Gutiérrez", fuente: "diarioelmarino 30-03-2026" },
  { region: "O'Higgins", cartera: "Mujer", nombre: "Carla Andrea Morales Maldonado", fuente: "diarioelmarino 30-03-2026", nota: "ex diputada" },
  { region: "O'Higgins", cartera: "Culturas", nombre: "Tamara Sherée", fuente: "diarioelmarino 30-03-2026" },
  { region: "O'Higgins", cartera: "Trabajo", nombre: "Carmen Gloria Manríquez", fuente: "diarioelmarino 30-03-2026" },
  { region: "O'Higgins", cartera: "Minería", nombre: "Carla Ortiz Castillo", fuente: "diarioelmarino 30-03-2026 · elindustrial.cl 05-06-2026" },
  { region: "O'Higgins", cartera: "Deporte", nombre: "María Isabel Moraga", fuente: "diarioelmarino 30-03-2026" },
  { region: "O'Higgins", cartera: "Transportes", nombre: "Julio Gutiérrez Sepúlveda", fuente: "diarioelmarino 27-03-2026" },
  { region: "O'Higgins", cartera: "Desarrollo Social", nombre: "Cristian Flores Valdés", fuente: "diarioelmarino 27-03-2026" },
  { region: "O'Higgins", cartera: "Bienes Nacionales", nombre: "Julio Ignacio Moncada Gómez", fuente: "eltipógrafo 27-03-2026 · radio Rancagua 27-03-2026 · bienesnacionales.cl 29-04-2026", nota: "cientista político; la prensa varía la grafía (Mondaca/Moncada Flores), el ministerio escribe Moncada" },

  // ==== MAULE — cargos con fuente ====
  { region: "Maule", cartera: "Vivienda", nombre: "Patricio Ponce", fuente: "vlnradio/24horas 26-03-2026", nota: "renunció semanas después (viernes 30-03 diario el Día)" },
  { region: "Maule", cartera: "Obras Públicas", nombre: "Yasna Cancino", fuente: "vlnradio 26-03-2026" },
  { region: "Maule", cartera: "Medio Ambiente", nombre: "Felipe Massardo", fuente: "vlnradio 26-03-2026" },
  { region: "Maule", cartera: "Economía", nombre: "Katherine Núñez", fuente: "diarioelcentro 25-03-2026" },
  { region: "Maule", cartera: "Educación", nombre: "Cristián Letelier", fuente: "diarioelcentro 25-03-2026" },
  { region: "Maule", cartera: "Seguridad Pública", nombre: "Germán Peralta", fuente: "diarioelcentro 30-03-2026", nota: "34 años en la PDI" },
  { region: "Maule", cartera: "Ciencia", nombre: "Macarena San Martín", fuente: "diarioelcentro 30-03-2026" },
  { region: "Maule", cartera: "Justicia", nombre: "Cristián Vargas", fuente: "diarioelcentro 30-03-2026" },
  { region: "Maule", cartera: "Deporte", nombre: "Francisca Samper", fuente: "diarioelcentro 30-03-2026", nota: "deportista paralímpica" },
  { region: "Maule", cartera: "Gobierno (Segegob)", nombre: "Hans Heyer", fuente: "diarioelcentro 30-03-2026" },
  { region: "Maule", cartera: "Mujer", nombre: "Fernanda Aguirre Torres", fuente: "diarioelcentro 30-03-2026" },
  { region: "Maule", cartera: "Energía", nombre: "Carlos Muena", fuente: "diarioelcentro 30-03-2026" },
  { region: "Maule", cartera: "Culturas", nombre: "Pablo Amaro Valenzuela", fuente: "diarioelcentro 30-03-2026" },

  // ==== ÑUBLE — gabinete completo (19 cargos) dprnuble 25/26/27/30/31-03 ====
  { region: "Ñuble", cartera: "Educación", nombre: "Felipe Vogel", fuente: "dprnuble 25-03-2026", nota: "magíster en liderazgo educacional" },
  { region: "Ñuble", cartera: "Medio Ambiente", nombre: "Angélica Cuevas", fuente: "dprnuble 25-03-2026", nota: "abogada" },
  { region: "Ñuble", cartera: "Economía", nombre: "Manuel Cofré", fuente: "dprnuble 25-03-2026", nota: "otrora seremi de Energía (Piñera)" },
  { region: "Ñuble", cartera: "Obras Públicas", nombre: "Luis Carrasco", fuente: "dprnuble 26-03-2026" },
  { region: "Ñuble", cartera: "Vivienda", nombre: "Carolina Navarrete", fuente: "dprnuble 26-03-2026", nota: "ex seremi de Bienes Nacionales Ñuble y consejera constitucional" },
  { region: "Ñuble", cartera: "Transportes", nombre: "Omar Sandoval", fuente: "dprnuble 27-03-2026", nota: "ingeniero, funcionario de carrera en la Subtel" },
  { region: "Ñuble", cartera: "Bienes Nacionales", nombre: "Rodrigo Herrera", fuente: "dprnuble 27-03-2026", nota: "abogado" },
  { region: "Ñuble", cartera: "Desarrollo Social", nombre: "Alan Ibáñez", fuente: "dprnuble 27-03-2026", nota: "kinesiólogo" },
  { region: "Ñuble", cartera: "Seguridad Pública", nombre: "Héctor Ponce", fuente: "dprnuble 30-03-2026", nota: "oficial (R) del Ejército" },
  { region: "Ñuble", cartera: "Gobierno (Segegob)", nombre: "Marco Muñoz", fuente: "dprnuble 30-03-2026", nota: "gerente del Grupo Marva" },
  { region: "Ñuble", cartera: "Justicia", nombre: "Natalia Reyes", fuente: "dprnuble 30-03-2026", nota: "abogada y académica UdeC" },
  { region: "Ñuble", cartera: "Culturas", nombre: "Natalie de la Hoz", fuente: "dprnuble 30-03-2026", nota: "abogada" },
  { region: "Ñuble", cartera: "Deporte", nombre: "Alfonso Millar", fuente: "dprnuble 30-03-2026", nota: "profesor de educación física" },
  { region: "Ñuble", cartera: "Energía", nombre: "Cristián Jaque Guzmán", fuente: "dprnuble 31-03-2026 · energia.gob.cl", nota: "ing. civil eléctrico" },
  { region: "Ñuble", cartera: "Trabajo", nombre: "Edmundo Novoa", fuente: "dprnuble 31-03-2026", nota: "ex director regional del IPS" },
  { region: "Ñuble", cartera: "Mujer", nombre: "María José Pérez", fuente: "dprnuble 31-03-2026", nota: "enfermera de la Udelbo" },

  // ==== BIOBÍO — elcontraste/diarioconcepción/latribuna ====
  { region: "Biobío", cartera: "Bienes Nacionales", nombre: "Matías Ruiz Fernández", fuente: "diarioconcepcion 30-03-2026", nota: "arquitecto UDD" },
  { region: "Biobío", cartera: "Ciencia", nombre: "Pedro Ramírez", fuente: "elcontraste 25-03-2026" },
  { region: "Biobío", cartera: "Culturas", nombre: "Carolina Tapia Clan", fuente: "diarioconcepcion 30-03-2026", nota: "2.º periodo (ya fue seremi 2019-2022)" },
  { region: "Biobío", cartera: "Deporte", nombre: "Gerardo Esparza", fuente: "elcontraste 25-03-2026" },
  { region: "Biobío", cartera: "Economía", nombre: "Gerald Rivera", fuente: "elcontraste 25-03-2026", nota: "cupo Demócratas; objetado" },
  { region: "Biobío", cartera: "Justicia", nombre: "Robert Contreras Reyes", fuente: "diarioconcepcion 30-03-2026", nota: "ex gobernador provincial de Concepción" },
  { region: "Biobío", cartera: "Medio Ambiente", nombre: "Mario Delann", fuente: "elcontraste 25-03-2026" },
  { region: "Biobío", cartera: "Minería", nombre: "Mauricio Suares", fuente: "elcontraste 25-03-2026" },
  { region: "Biobío", cartera: "Vivienda", nombre: "Luis Anselmo Villagra", fuente: "elcontraste 25-03-2026" },
  { region: "Biobío", cartera: "Mujer", nombre: "Antariét Vila Compagnon", fuente: "diarioconcepcion 30-03-2026", nota: "bioquímica; nombramiento sin efecto (El Dínamo 16-04)" },
  { region: "Biobío", cartera: "Obras Públicas", nombre: "José Piñas", fuente: "elcontraste 25-03-2026", nota: "concejal de Concepción" },
  { region: "Biobío", cartera: "Segegob", nombre: "Daniel Pacheco", fuente: "elcontraste 25-03-2026", nota: "concejal de Concepción" },
  { region: "Biobío", cartera: "Seguridad Pública", nombre: "Edson Bernal", fuente: "elcontraste 25-03-2026" },
  { region: "Biobío", cartera: "Trabajo", nombre: "Camila Álvarez", fuente: "elcontraste 25-03-2026" },
  { region: "Biobío", cartera: "Transportes", nombre: "Henry Campos", fuente: "elcontraste 25-03-2026", nota: "ex alcalde de Talca" },
  { region: "Biobío", cartera: "Hacienda", nombre: "Ronald Ruf", fuente: "elcontraste 25-03-2026" },
  { region: "Biobío", cartera: "Desarrollo Social", nombre: "Daniel Manchileo", fuente: "elcontraste 25-03-2026" },
  { region: "Biobío", cartera: "Educación", nombre: "Alexander Nanjarí", fuente: "elcontraste 26-03-2026", nota: "renuncia sin asumir (polémica publicaciones); decreto nunca ejecutado" },
  { region: "Biobío", cartera: "Energía", nombre: "Andrea de la Barra", fuente: "elcontraste 25-03-2026", nota: "no cumple requisitos; podría asumir Ana Aran" },

  // ==== LA ARAUCANÍA · dprlaaraucania 01-04 + confirmaciones ====
  { region: "La Araucanía", cartera: "Justicia", nombre: "Stephanie Caming", fuente: "dprlaaraucania 01-04-2026", nota: "abogada, ex seremi (2019-2022)" },
  { region: "La Araucanía", cartera: "Deporte", nombre: "Mauricio Martínez Jaramillo", fuente: "dprlaaraucania 01-04-2026" },
  { region: "La Araucanía", cartera: "Mujer", nombre: "María Carolina Lagos Jofré", fuente: "dprlaaraucania 01-04-2026", nota: "ing. civil industrial, ex INJUV" },
  { region: "La Araucanía", cartera: "Energía", nombre: "Patrick Dungan ", fuente: "dprlaaraucania 01-04-2026", nota: "nombramiento retirado tras no presentarse al trabajo (latercera) → luego Jorge Rathgeb (27-04)" },
  { region: "La Araucanía", cartera: "Trabajo", nombre: "Francisco Mejías", fuente: "dprlaaraucania 01-04-2026" },
  { region: "La Araucanía", cartera: "Ciencia", nombre: "Odilba Saray Salazar", fuente: "dprlaaraucania 01-04-2026" },
  { region: "La Araucanía", cartera: "Seguridad Pública", nombre: "Mario Sepúlveda Barco", fuente: "dprlaaraucania 01-04-2026", nota: "ex jefe de la XVIª Zona de Carabineros" },
  { region: "La Araucanía", cartera: "Bienes Nacionales", nombre: "Juan Guillermo Rojas Casas", fuente: "alertarepublic equipo 27-03-2026", nota: "abogado" },
  { region: "La Araucanía", cartera: "Obras Públicas", nombre: "Reginaldo Liste", fuente: "tiempo21 27-03-2026" },
  { region: "La Araucanía", cartera: "Transportes", nombre: "Rodrigo Lagos Sagredo", fuente: "dprlaaraucania.dpr.gob.cl 27-03-2026 · subtrans.gob.cl · tiempo21.cl 27-03-2026", nota: "ing. civil industrial, ex director regional de Aeropuertos del MOP" },
  { region: "La Araucanía", cartera: "Hacienda", nombre: "Francisco Fuster Vasátes", fuente: "araucanianoticias 27-04-2026" },
  { region: "La Araucanía", cartera: "Energía", nombre: "Jorge Rathgeb Quiero", fuente: "araucanianotic 27-04-2026", nota: "reemplaza a Patrick Dungan" },

  // ==== LOS RÍOS — dprlosrios completo (Radio Austral 21-04) ====
  { region: "Los Ríos", cartera: "Educación", nombre: "Orlando Carlos Crot Pérez", fuente: "dprlosrios.dpr.gob.cl 25-03-2026", nota: "profesor de Estado en Castellano; ex seremi de Educación de Los Ríos (2010-2014)" },
  { region: "Los Ríos", cartera: "Medio Ambiente", nombre: "Enrique Gillmore Carmona", fuente: "dprlosrios.dpr.gob.cl 25-03-2026" },
  { region: "Los Ríos", cartera: "Economía", nombre: "Rafael Foradori Peralta", fuente: "dprlosrios.dpr.gob.cl 25-03-2026", nota: "periodista, ex director regional del Sence; concejal de Valdivia" },
  { region: "Los Ríos", cartera: "Vivienda", nombre: "Cristián Arriagada Patíño", fuente: "rioenlinea.cl 26-03-2026", nota: "ingeniero" },
  { region: "Los Ríos", cartera: "Transportes", nombre: "Juan Pablo Alvarado Lecaros", fuente: "dprlosrios.dpr.gob.cl 27-03-2026" },
  { region: "Los Ríos", cartera: "Desarrollo Social", nombre: "Daniela Paz Silva Vidal", fuente: "dprlosrios.dpr.gob.cl 27-03-2026" },
  { region: "Los Ríos", cartera: "Mujer", nombre: "Oriet Montecinos Durán", fuente: "diariodevaldivia.cl 30-03-2026", nota: "docente" },
  { region: "Los Ríos", cartera: "Gobierno (Segegob)", nombre: "Ane Contreras Álvarez", fuente: "diariodevaldivia.cl 30-03-2026", nota: "ingeniera en Administración de Empresas; consejera regional (Partido Republicano)" },
  { region: "Los Ríos", cartera: "Justicia", nombre: "Daniela Coello", fuente: "mivaldivia.cl 30-03-2026", nota: "abogada, jueza de Policía Local" },
  { region: "Los Ríos", cartera: "Culturas", nombre: "Hugo Ortiz de Filippi", fuente: "mivaldivia.cl 30-03-2026", nota: "exsenador, ex seremi del Trabajo" },
  { region: "Los Ríos", cartera: "Bienes Nacionales", nombre: "Rodrigo Oñate", fuente: "mivaldivia.cl 30-03-2026", nota: "abogado; ex seremi de Justicia" },
  { region: "Los Ríos", cartera: "Seguridad Pública", nombre: "Juan Agustín Meléndez", fuente: "dprlosrios.dpr.gob.cl 31-03", nota: "ex Fiscal Regional de Los Ríos, fiscal nacional subrogante" },
  { region: "Los Ríos", cartera: "Energía", nombre: "Juan Manuel Taladriz Eguiluz", fuente: "energia.gob.cl 31-03-2026", nota: "ingeniero comercial; ex consejero regional" },
  { region: "Los Ríos", cartera: "Ciencia", nombre: "Mauricio Barría Pailaquilén", fuente: "medicina.uach.cl 02-04-2026 · diario.uach.cl 02-04-2026", nota: "académico de la Facultad de Medicina UACh" },
  { region: "Los Ríos", cartera: "Minería", nombre: "Karina Silva", fuente: "rioenlinea.cl 06-04-2026 · SoyChile Valdivia 07-04-2026 · Diario de Valdivia 06-04-2026", nota: "abogada, diplomado en Alta Dirección Pública" },
  { region: "Los Ríos", cartera: "Obras Públicas", nombre: "Edinson Rivera García", fuente: "rioenlinea.cl 07-04-2026", nota: "ing. civil industrial; reemplaza a Jorge Salazar, nombramiento dejado sin efecto en menos de 24 h" },
  { region: "Los Ríos", cartera: "Trabajo", nombre: "Denisse Merino", fuente: "radioaustral 21-04-2026" },
  { region: "Los Ríos", cartera: "Deporte", nombre: "Roberto Buchhorsts Vargas", fuente: "radioaustral 21-04-2026 · noticiaslosrios.cl 21-04-2026", nota: "profesor de educación física, magíster en liderazgo educacional; completó el gabinete regional tras 41 días" },

  // ==== LOS LAGOS — patagoniaradio/elcalbucano/cooperativa ====
  { region: "Los Lagos", cartera: "Medio Ambiente", nombre: "Lorena Leichtle Bertín", fuente: "elcalbucano 25-03-2026", nota: "veterinaria (RN)" },
  { region: "Los Lagos", cartera: "Seguridad Pública", nombre: "Francisco Muñoz Le Bretón", fuente: "cooperativa 31-03-2026", nota: "ex gobernador de Llanquihue (UDI)" },
  { region: "Los Lagos", cartera: "Gobierno (Segegob)", nombre: "Rodrigo Díaz González", fuente: "cooperativa 31-03-2026", nota: "periodista y ing. agrónomo (PR)" },
  { region: "Los Lagos", cartera: "Agricultura", nombre: "Francisco Cárcamo Hernández", fuente: "minagri.gob.cl 30-03-2026", nota: "ex consejero regional por Chiloé" },
  { region: "Los Lagos", cartera: "Mujer", nombre: "Karen Berríos Guerra", fuente: "cooperativa 31-03-2026", nota: "PR" },
  { region: "Los Lagos", cartera: "Deporte", nombre: "Fernando Binder Álvarez", fuente: "cooperativa 31-03-2026", nota: "Independiente" },
  { region: "Los Lagos", cartera: "Trabajo", nombre: "Jorge Moreno Oyanadel", fuente: "cooperativa 31-03-2026", nota: "ex seremi de Bienes Nacionales (UDI)" },
  { region: "Los Lagos", cartera: "Energía", nombre: "Andrés Niklitschek Strauch", fuente: "elcalbucano 10-04-2026", nota: "reemplaza a Jorge Ravelo, cuyo nombramiento se revocó 08-04-2026" },
  { region: "Los Lagos", cartera: "Transportes", nombre: "Rodrigo Böttger Quiroz", fuente: "cooperativa 31-03-2026", nota: "independiente" },
  { region: "Los Lagos", cartera: "Economía", nombre: "Gisela Strauch Stange", fuente: "elcalbucano 10-04-2026", nota: "ing. comercial (IND)" },
  { region: "Los Lagos", cartera: "Educación", nombre: "Dalmiro Yáñez Martínez", fuente: "lamega 06-04-2026 · elrepuertero 06-04-2026 · patagoniaradio 10-04-2026", nota: "ingeniero en Administración (RN), ex director regional del IPS 2020-2023; asumió 06-04-2026 tras anularse el decreto de Patricia Dinamarca Reyes" },
  { region: "Los Lagos", cartera: "Justicia", nombre: "Claudio Valdivia Romero", fuente: "cooperativa 31-03-2026", nota: "RN" },
  { region: "Los Lagos", cartera: "Bienes Nacionales", nombre: "Nicolás Yunge Jürgensen", fuente: "cooperativa 31-03-2026", nota: "renunció a su concejalía para asumir (PR)" },
  { region: "Los Lagos", cartera: "Culturas", nombre: "Eduardo Leiva Zumelzu", fuente: "cooperativa 31-03-2026", nota: "IND; en agosto 2026 le sucede Karen Lindh" },
  { region: "Los Lagos", cartera: "Vivienda", nombre: "Mario Marchant Martínez", fuente: "cooperativa 27-03-2026", nota: "PR" },
  { region: "Los Lagos", cartera: "Obras Públicas", nombre: "Jairo Quinteros", fuente: "cooperativa 28-03-2026", nota: "ing. civil, ex inspector fiscal de obras del MOP" },
  { region: "Los Lagos", cartera: "Desarrollo Social", nombre: "Carlos Seitz Aspée", fuente: "midesof.gob.cl 27-03-2026", nota: "ing. forestal" },

  // ==== AYSÉN — dprasén/eldivisadero (nombres validados en sesión) ====
  { region: "Aysén", cartera: "Medio Ambiente", nombre: "Eugenio Canales", fuente: "eldivisadero 31-03-2026", nota: "independiente" },
  { region: "Aysén", cartera: "Educación", nombre: "Tomás Valenzuela", fuente: "aysen.mineduc.cl 25-03-2026" },
  { region: "Aysén", cartera: "Economía", nombre: "Rodrigo Aguilera", fuente: "dprasén 26-03-2026", nota: "PRCh" },
  { region: "Aysén", cartera: "Vivienda", nombre: "Fabián Rojas Muñoz", fuente: "dprasén 27-03-2026", nota: "ex seremi de Vivienda en 2.º gobierno de Piñera (RN)" },
  { region: "Aysén", cartera: "Obras Públicas", nombre: "Luis Prieto Epuyao", fuente: "eldivisadero 27-03-2026", nota: "UDI" },
  { region: "Aysén", cartera: "Gobierno (Segegob)", nombre: "Bárbara Aldunate Ortúzar", fuente: "eldivisadero 31-03-2026", nota: "RN" },
  { region: "Aysén", cartera: "Justicia", nombre: "Andrea Vera Ponce", fuente: "eldivisadero 31-03-2026", nota: "UDI" },
  { region: "Aysén", cartera: "Ciencia", nombre: "Gabriel Pérez", fuente: "eldivisadero 31-03-2026", nota: "RN" },
  { region: "Aysén", cartera: "Culturas", nombre: "Ángela Valdebenito", fuente: "eldivisadero 31-03-2026", nota: "UDI; renunció el 17-04-2026 acusando violencia digital" },
  { region: "Aysén", cartera: "Deporte", nombre: "Jorge Ojeda", fuente: "dprasén 31-03-2026", nota: "EVO" },
  { region: "Aysén", cartera: "Minería", nombre: "José Luis Osorio", fuente: "redimin 14-04-2026", nota: "PRCh" },
  { region: "Aysén", cartera: "Energía", nombre: "José Luis Amenábar", fuente: "dprasén 31-03-2026", nota: "IND" },
  { region: "Aysén", cartera: "Mujer", nombre: "Roxana Nahuel", fuente: "dprasén 31-03-2026", nota: "asume 01-04" },
  { region: "Aysén", cartera: "Seguridad Pública", nombre: "Jean Paul Zimmermann", fuente: "dprasén 31-03-2026" },
  { region: "Aysén", cartera: "Desarrollo Social", nombre: "Marcia Raphael", fuente: "dprasén 31-03-2026", nota: "ex diputada RN; midesof lista a Luz Valeria Villegas Ojeda como sucesora" },
  { region: "Aysén", cartera: "Transportes", nombre: "Verónica Figueroa", fuente: "dprasén 31-03-2026", nota: "concejal de Coyhaique (IND)" },
  { region: "Aysén", cartera: "Trabajo", nombre: "Sebastián Solís", fuente: "diarioregionalaysen.cl 02-04-2026", nota: "ing. comercial, ex director Cámara de Comercio; completa el gabinete" },

  // ==== MAGALLANES — laprensaaustral/itvpatagonia/portal12 ====
  { region: "Magallanes", cartera: "Medio Ambiente", nombre: "Gonzalo Rosenfeld Sekulovic", fuente: "mma.gob.cl 25-03-2026", nota: "ex director regional de FOSIS" },
  { region: "Magallanes", cartera: "Vivienda", nombre: "José Rodolfo Guajardo Barría", fuente: "dialogosur.cl 25-03-2026", nota: "constructor civil, ex vp de RN" },
  { region: "Magallanes", cartera: "Transportes", nombre: "Allan Stöwhas", fuente: "itvpatagonia.com 27-03-2026", nota: "ing. en informática, ex vicepresidente regional del PR" },
  { region: "Magallanes", cartera: "Bienes Nacionales", nombre: "Lorena Díaz", fuente: "itvpatagonia.com 27-03-2026", nota: "abogada U. de Magallanes" },
  { region: "Magallanes", cartera: "Gobierno (Segegob)", nombre: "Ángel Roa Alegría", fuente: "dialogosur.cl 31-03-2026" },
  { region: "Magallanes", cartera: "Desarrollo Social", nombre: "Jenniffer Rojas García", fuente: "ovejeronoticias.cl 30-03-2026", nota: "asistente social (RN)" },
  { region: "Magallanes", cartera: "Deporte", nombre: "Jacques Roux", fuente: "ovejeronoticias.cl 30-03-2026" },
  { region: "Magallanes", cartera: "Obras Públicas", nombre: "Alejandro Marusic", fuente: "itvpatagonia.com 02-04-2026" },
  { region: "Magallanes", cartera: "Economía", nombre: "Francisco Birke", fuente: "itvpatagonia.com 02-04-2026" },
  { region: "Magallanes", cartera: "Justicia", nombre: "Cristóbal Fernández", fuente: "itvpatagonia.com 02-04-2026", nota: "abogado U. Finis Terrae, ex seremi en gobierno de Piñera" },
  { region: "Magallanes", cartera: "Ciencia", nombre: "Carlos Olave", fuente: "laprensaaustral.cl 01-04-2026", nota: "UDI" },
  { region: "Magallanes", cartera: "Energía", nombre: "Marco Antonio Pinto Torres", fuente: "laprensaaustral.cl 01-04-2026", nota: "biólogo marino" },
  { region: "Magallanes", cartera: "Culturas", nombre: "Rodrigo Bravo Garrido", fuente: "laprensaaustral.cl 01-04-2026", nota: "independiente" },
  { region: "Magallanes", cartera: "Mujer", nombre: "Gabriela Sánchez Cañete", fuente: "ovejeronoticias.cl 10-04-2026" },
  { region: "Magallanes", cartera: "Educación", nombre: "José Raúl Alvarado Díaz", fuente: "laprensaaustral.cl 07-04-2026", nota: "ex director del Liceo Industrial; Sol Aguila no se oficializó" },
];