-- Legacy runtime tables retained during the Cambiometro migration.
CREATE TABLE IF NOT EXISTS partidos (id TEXT PRIMARY KEY, nombre TEXT NOT NULL, sigla TEXT UNIQUE NOT NULL, logo_url TEXT, color_hex TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS politicos (id TEXT PRIMARY KEY, rut TEXT UNIQUE, nombre_completo TEXT NOT NULL, cargo TEXT NOT NULL, partido_id TEXT, distrito_region TEXT NOT NULL, numero_distrito INTEGER, foto_url TEXT, twitter_handle TEXT, comisiones TEXT, fecha_inicio_periodo TEXT, fecha_fin_periodo TEXT, activo INTEGER DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS declaraciones_patrimonio (id TEXT PRIMARY KEY, politico_id TEXT NOT NULL, fecha_declaracion TEXT NOT NULL, tipo_declaracion TEXT DEFAULT 'Ordinaria', valor_patrimonio_total REAL DEFAULT 0, inmuebles_json TEXT, vehiculos_json TEXT, sociedades_json TEXT, pasivos_json TEXT, ingresos_json TEXT, hash_contenido TEXT, url_fuente TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cambios_patrimonio (id TEXT PRIMARY KEY, politico_id TEXT NOT NULL, fecha_deteccion TEXT NOT NULL, tipo_cambio TEXT NOT NULL, campo_afectado TEXT NOT NULL, valor_anterior TEXT, valor_nuevo TEXT, delta_monetario REAL, nivel_alerta TEXT DEFAULT 'Info', publicado INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS gastos_operacionales (id TEXT PRIMARY KEY, politico_id TEXT NOT NULL, ano INTEGER, mes TEXT NOT NULL, categoria TEXT NOT NULL, monto_bruto REAL, monto_clp REAL, monto_ajustado_regional REAL, indice_territorial REAL, url_fuente TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS entidades_relacionadas (id TEXT PRIMARY KEY, politico_id TEXT NOT NULL, nombre_relacionado TEXT NOT NULL, rut_relacionado TEXT, tipo_relacion TEXT NOT NULL, grado_parentesco TEXT, cargo_o_empresa TEXT, monto_contrato REAL, alerta_nepotismo INTEGER DEFAULT 0, fuente TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS proyectos_ley (id TEXT PRIMARY KEY, boletin TEXT UNIQUE NOT NULL, titulo TEXT NOT NULL, descripcion TEXT, estado TEXT, fecha_ingreso TEXT, fecha_votacion TEXT, palabras_clave TEXT, url_congreso TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS votaciones (id TEXT PRIMARY KEY, politico_id TEXT NOT NULL, proyecto_ley_id TEXT NOT NULL, fecha_votacion TEXT NOT NULL, voto TEXT NOT NULL, sala TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS incoherencias_rrss (id TEXT PRIMARY KEY, politico_id TEXT NOT NULL, tweet_id TEXT NOT NULL, texto_tweet TEXT NOT NULL, fecha_tweet TEXT NOT NULL, proyecto_ley_id TEXT, voto_emitido TEXT, polaridad_tweet TEXT, tipo_incoherencia TEXT NOT NULL, score_confianza REAL, verificado_manual INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audiencias_lobby (id TEXT PRIMARY KEY, politico_id TEXT NOT NULL, sujeto_activo TEXT NOT NULL, rut_sujeto TEXT, materia TEXT NOT NULL, fecha_audiencia TEXT NOT NULL, resultado_votacion TEXT, alerta_captura INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS alertas_anomalias (id TEXT PRIMARY KEY, politico_id TEXT NOT NULL, fecha TEXT NOT NULL, tipo_alerta TEXT NOT NULL, nivel_gravedad TEXT NOT NULL, descripcion TEXT NOT NULL, evidencia_json TEXT, publicado_redes INTEGER DEFAULT 0, publicado_telegram INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS asistencia (id TEXT PRIMARY KEY, politico_id TEXT NOT NULL, fecha_sesion TEXT NOT NULL, tipo_sesion TEXT, asistio INTEGER NOT NULL, justificada INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_politicos_cargo ON politicos(cargo);
CREATE INDEX IF NOT EXISTS idx_politicos_partido ON politicos(partido_id);
CREATE INDEX IF NOT EXISTS idx_gastos_politico_ano ON gastos_operacionales(politico_id, ano, mes);
CREATE INDEX IF NOT EXISTS idx_votaciones_politico ON votaciones(politico_id);
